
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParkingBayService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.1.171:8889/Service/ParkingBayService?wsdl")
public class ParkingBayService
    extends Service
{

    private final static URL PARKINGBAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARKINGBAYSERVICE_EXCEPTION;
    private final static QName PARKINGBAYSERVICE_QNAME = new QName("http://tempuri.org/", "ParkingBayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.1.171:8889/Service/ParkingBayService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARKINGBAYSERVICE_WSDL_LOCATION = url;
        PARKINGBAYSERVICE_EXCEPTION = e;
    }

    public ParkingBayService() {
        super(__getWsdlLocation(), PARKINGBAYSERVICE_QNAME);
    }

    public ParkingBayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARKINGBAYSERVICE_QNAME, features);
    }

    public ParkingBayService(URL wsdlLocation) {
        super(wsdlLocation, PARKINGBAYSERVICE_QNAME);
    }

    public ParkingBayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARKINGBAYSERVICE_QNAME, features);
    }

    public ParkingBayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParkingBayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IParkingBayService
     */
    @WebEndpoint(name = "BasicHttpBinding_IParkingBayService")
    public IParkingBayService getBasicHttpBindingIParkingBayService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IParkingBayService"), IParkingBayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IParkingBayService
     */
    @WebEndpoint(name = "BasicHttpBinding_IParkingBayService")
    public IParkingBayService getBasicHttpBindingIParkingBayService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IParkingBayService"), IParkingBayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARKINGBAYSERVICE_EXCEPTION!= null) {
            throw PARKINGBAYSERVICE_EXCEPTION;
        }
        return PARKINGBAYSERVICE_WSDL_LOCATION;
    }

}
